name: simba
description: "SimbA — Simbioz Active. Поиск и размещение услуг."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  go_router: ^17.2.3
  flutter_riverpod: ^3.3.1
  google_fonts: ^8.1.0
  intl: ^0.20.2

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  vector_map_tiles: ^8.0.0

  image_picker: ^1.2.2
  pin_code_fields: ^9.3.0
  iconsax_plus: ^1.0.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.1
  http: ^1.2.2
  geolocator: ^13.0.2
  pocketbase: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher/ic_launcher.webp"
  adaptive_icon_background: "#1369CD"
  adaptive_icon_foreground: "assets/launcher/ic_launcher.webp"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
